# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            je pense, donc je suis

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  Welcome to Wenfeng's Blog.

# The tags listed as entries in the sidebar
sidebar_tags:     [docker, unit-test, react, coreos, cluster, kubernetes, network, git, shell, python, coroutine]

# Fallback image and color if not overwritten for tag or post
#image:            /public/img/nap.jpg
color:            '#A85641'

author:
  name:           'wenfeng'

  # Setting social media usernames will add icons at the bottom of the sidebar
  github:         Wenfeng-GAO

  # Setting a disqus username will enable the comment section
  disqus:         wenfeng

  # This photo will be used in the about section
  photo:          /public/img/me.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hi, I'm Wenfeng, another happy coder and daily dreamer, welcome to my technique
    blog, feel free to share your ideas by commentting or emailing.

    Hi，我是文枫，欢迎来到我的技术博客，欢迎相互交流。

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
